### ISSUE TITLE
Where did the library pdftables go?

### ISSUE THREAD

**Issue by MichaelJAndy** [scraperwiki/pdftables-terms#4]
Hey, do you know where i can find this? https://github.com/scraperwiki/pdftables

It used to link to your public space here, seems like it's gone!

**Comment by StevenMaude** [comment]
Wow, this issue was buried away :)

We've been improving the `pdftables` extraction code privately over the past year and run it as a web app at https://pdftables.com

For reference, the source as of the last commit we made public is [available on GitHub](https://github.com/drj11/pdftables). Viacheslav Naydenov has made this code [Python 3 compatible](https://github.com/vnaydionov/pdftables).
